apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-kong
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
    verbs:
      - create
      - patch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - patch
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-kong-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-kong
subjects:
  - kind: ServiceAccount
    name: redhat-kong-gitops-argocd-application-controller
    namespace: openshift-gitops
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kong-role
  namespace: kong
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - anyuid
    resources:
      - securitycontextconstraints
    verbs:
      - use
  - verbs:
      - create
      - get
    apiGroups:
      - ''
    resources:
      - secrets
      - configmap
      - services
  - verbs:
      - get
    apiGroups:
      - route.openshift.io
    resources:
      - routes
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kong-role-binding
  namespace: kong
subjects:
  - kind: ServiceAccount
    name: kong
    namespace: kong
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kong-role
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-argo
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - verbs:
      - get
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - apiGroups:
      - argoproj.io
    resources:
      - appprojects
    verbs:
      - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-argo-binding
subjects:
  - kind: ServiceAccount
    namespace: kong
    name: kong
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-argo
