apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kong-kong-admin
  namespace: kong
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  port:
    targetPort: kong-admin
  to:
    kind: Service
    name: kong-kong-admin
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kong-kong-manager
  namespace: kong
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  port:
    targetPort: kong-manager
  to:
    kind: Service
    name: kong-kong-manager
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kong-kong-manager-tls
  namespace: kong
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  port:
    targetPort: kong-manager-tls
  tls:
    termination: passthrough
  to:
    kind: Service
    name: kong-kong-manager
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kong-kong-admin-tls
  namespace: kong
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  port:
    targetPort: kong-admin-tls
  tls:
    termination: passthrough
  to:
    kind: Service
    name: kong-kong-admin
