apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: kong
  labels:
    app: kong
  namespace: kong
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  config: {}
  ingress:
    enabled: true
  dashboardLabelSelector:
  - matchExpressions:
      - { key: app, operator: In, values: [ kong ] }   
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-ds
  labels:
    app: kong
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: kong-prometheus-ds
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-operated:9090
      isDefault: true
      version: 1
      editable: true
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata: 
  name: kong-dashboard
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: kong
spec:
  url: https://raw.githubusercontent.com/Kong/kong-plugin-prometheus/master/grafana/kong-official.json
  datasources:
    - inputName: "DS_PROMETHEUS"
      datasourceName: "Prometheus"