apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
---
apiVersion: v1
kind: Namespace
metadata:
  name: bookinfo
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
