apiVersion: v1
kind: Service
metadata:
  name: {{ include "ratings.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: ratings
    service: ratings
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: ratings
