apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: controlplane
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: v0.21.0
    helm:
      values: |
        global:
          openshift: true
        server:
          ha:
            enabled: true
            replicas: 2 # set to the number of worker nodes
            raft:
              enabled: true
              tls: false
  destination:
    name: cp
    namespace: vault
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle