apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-gitops
    name: in-cluster
  project: default
  source:
    path: openshift-gitops/apps/charts
    repoURL: https://github.com/hybrid-cloud-patterns/kong-gateway.git
    targetRevision: kong-pattern
  syncPolicy:
    automated: # automatically sync repo changes
      prune: true
      selfHeal: true
      allowEmpty: true