apiVersion: batch/v1
kind: Job
metadata:
  name: cert-secret
  namespace: {{ .Values.global.namespace }}
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: {{ .Values.kong.deployment.serviceAccount.name }}
      containers:
      - name: generate-cert-secret
        image: quay.io/ecosystem-appeng/cert-generator:1.0
        securityContext:
          runAsUser: 0
        command:
         - "/bin/bash"
         - "-c"
         - "oc create secret tls kong-cluster-cert --cert=./cluster.crt --key=./cluster.key -n {{ .Values.global.namespace }} && echo 'kong certificate secret created'"
      restartPolicy: Never  