apiVersion: v1
kind: Secret
metadata:
  name: kong-enterprise-license
  namespace: {{ .Values.global.namespace }}
  annotations:
    avp.kubernetes.io/path: "secret/data/hub/kong"
type: Opaque
stringData:
  license: "<license>"