{{ if eq .Values.kong.env.role "data_plane" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.name }}-enterprise-license
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  license: "<license>"
{{ end }}
---
{{ if eq .Values.kong.env.role "control_plane" }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: license
  namespace: {{ .Values.global.name }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: {{ .Values.global.name }}-enterprise-license
    template:
      type: Opaque
      data:
        license: |-
          {{ "{{ .mysecret | toString }}" }}
  data:
  - secretKey: mysecret
    remoteRef:
      key: {{ .Values.secretsBase.key }}/{{ .Values.global.name }}
      property: license
{{ end }}