{{ if eq .Values.persistence.type "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{ end }}