apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: {{ .Values.global.namespace }}
stringData:
  database-name: {{ .Values.dbname }}
  database-password: {{ .Values.password }}
  database-user: {{ .Values.username }}
