apiVersion: v1
kind: Service
metadata:
  name: {{ include "reviews.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: reviews
    service: reviews
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: reviews
